# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8566c547b0cb92843d44a648d8ed1b00e119e38630fb045ef95da4b38232db4d8725dc1fa48cc35986ec35e493c7a1b04632f7e1ca0335c7a7804299f0723b4f

test:
  secret_key_base: 93fdda5a88f1f1edca172cdfd0571ba45c1b92e94eceb968daef99ade873ccc575a4bf4ae808e2497545bb719fd35d1f1002e474fb0a6e7e55eaae4384479b47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
